services:
  - type: web
    name: museum-ticket-system
    env: python
    buildCommand: |
      # Install backend dependencies
      pip install -r requirements.txt
      cd frontend/webpage && npm install && npx vite build
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ORS_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: MONGO_URI
        sync: false
