services:
  - type: web
    name: museum-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ORS_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: MONGO_URI
        sync: false
